# Generated by Django 4.2.2 on 2023-06-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usertrainerapp', '0010_alter_trainingmodule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
